---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: fedora-latest
    image: fedora:latest
  - name: fedora-rawhide
    image: fedora:rawhide
provisioner:
  name: ansible
  playbooks:
    converge: ../default/playbook.yml
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  directory: ../default/tests/
  lint:
    name: flake8
