name: Test

on: [push]

env:
  python_version: 3.7
  pipenv_version: 2018.11.26

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Use Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.python_version }}
      - name: Restore cache if available
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Restore pipenv cache if available
        uses: actions/cache@v1
        with:
          path: ~/.cache/pipenv
          key: ${{ runner.os }}-pipenv-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-
      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1
        with:
          version: ${{ env.pipenv_version }}
      - name: Install dependencies
        run: pipenv sync --dev
      - name: Run lint
        run: |
          pipenv run molecule lint -s default
          pipenv run molecule lint -s macos
          pipenv run molecule lint -s macos_brew
  test_macos:
    strategy:
      matrix:
        scenario:
          - macos
          - macos_brew
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.python_version }}
      - name: Restore cache if available
        uses: actions/cache@v1
        with:
          path: ~/Library/Caches/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Restore pipenv cache if available
        uses: actions/cache@v1
        with:
          path: ~/Library/Caches/pipenv
          key: ${{ runner.os }}-pipenv-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-
      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1
        with:
          version: ${{ env.pipenv_version }}
      - name: Install dependencies
        run: pipenv sync --dev
      - name: Run provisioning on localhost
        run: pipenv run molecule test -s ${{ matrix.scenario }}
  test_linux:
    strategy:
      matrix:
        os:
          - ubuntu-18.04
          - ubuntu-16.04
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Use Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.python_version }}
      - name: Restore cache if available
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Restore pipenv cache if available
        uses: actions/cache@v1
        with:
          path: ~/.cache/pipenv
          key: ${{ runner.os }}-pipenv-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-
      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1
        with:
          version: ${{ env.pipenv_version }}
      - name: Install dependencies
        run: pipenv sync --dev
      - name: Run provisioning on localhost
        run: pipenv run ansible-playbook tests/test.yml -i tests/inventory
        env:
          ANSIBLE_ACTION_WARNINGS: False
          ANSIBLE_LOCALHOST_WARNING: False
          ANSIBLE_SYSTEM_WARNINGS: False
